# Generated by Django 3.2 on 2023-02-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nim_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_number', models.CharField(max_length=256)),
                ('interface_description', models.CharField(max_length=256)),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='nim_app.devices')),
            ],
        ),
    ]
