# Generated by Django 3.2 on 2023-02-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nim_app', '0002_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='rack_location',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
