# Generated by Django 3.2 on 2023-02-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nim_app', '0003_devices_rack_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='interface_detail',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
