# Generated by Django 3.2 on 2023-03-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nim_app', '0004_interface_interface_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIA_clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIP', models.CharField(max_length=256)),
                ('primary_ip', models.GenericIPAddressField()),
                ('secondary_ip', models.GenericIPAddressField()),
                ('client_name', models.CharField(max_length=256)),
                ('sr_number', models.CharField(max_length=256)),
                ('bandwidth', models.CharField(max_length=256)),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datacenter', to='nim_app.datacenter')),
            ],
        ),
    ]
